# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_stream.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'audio_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61udio_stream.proto\x12\x05\x61udio\"#\n\x0c\x41udioRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\"&\n\rAudioResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2K\n\x0b\x41udioStream\x12<\n\x0bStreamAudio\x12\x13.audio.AudioRequest\x1a\x14.audio.AudioResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=29
  _globals['_AUDIOREQUEST']._serialized_end=64
  _globals['_AUDIORESPONSE']._serialized_start=66
  _globals['_AUDIORESPONSE']._serialized_end=104
  _globals['_AUDIOSTREAM']._serialized_start=106
  _globals['_AUDIOSTREAM']._serialized_end=181
# @@protoc_insertion_point(module_scope)
