# Generated by Django 4.1.5 on 2024-12-21 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('isActived', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('context', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chat')),
            ],
        ),
    ]
