# Generated by Django 5.1.4 on 2024-12-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_message_options_rename_message_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ai_name',
            field=models.CharField(default='AI Assistant', max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='capabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='personality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
