# Generated by Django 5.1.4 on 2024-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_chat_ai_name_chat_capabilities_chat_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='humor_level',
            field=models.IntegerField(default=75),
        ),
    ]
